### ISSUE TITLE
GitHub - Change all icons to link to Common folder on docs - delete all unused icons in Media folder on Help

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#461] opened 2022-09-22 08:15 UTC
Changing all icons to the Common folder in docs - delete all unused icons in Media folder under help

**Comment by digitaldiina** [comment] 2022-09-22 12:41
This issue is a duplicate of #380.

**Closed by digitaldiina** 2022-09-22 12:41 UTC
Labels: guide-admin, guide-user

**Comment by kirstiaa** [comment] 2022-09-22 12:50
@digitaldiina Sorry, I added this in a different board - didn't think about all the different boards issues might be added :p 
Is there a way to show an issue in multiple boards?
