### ISSUE TITLE
Feedback for CK editor - attachmentIds retrieval

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/superoffice-docs#286] opened 2022-04-20 13:32 UTC
Missing documentation related to retrieving attachment id's, see:

https://community.superoffice.com/en/technical/forums/api-forums/service-crmscript/custom-screens---how-to-get-the-attachmentid-of-the-attachments-added-in-the-ck-editor-form-element/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [blogic_ck_editor](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/ui/blogic/reference/ck-editor.md/#L1)

**Comment by kronicz** [comment] 2022-05-18 11:06
Duplicate of #265

**Closed by kronicz** 2022-05-18 11:06 UTC
Labels: duplicate, doc-bug
