### ISSUE TITLE
Learn: Translation 1st version - sv, de, da, nl

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#748] opened 2023-06-19 09:46 UTC

**Comment by digitaldiina** [comment] 2023-07-10 07:15
This is a duplicate of issue #744. Also, the branch must be split to cover only 1 language per branch to keep the number of changed files reasonable. Otherwise the PR diff will time out.

Several changes are also necessary in each language, see [checklist](#744).

**Closed by digitaldiina** 2023-07-10 07:15 UTC
Labels: learn
