### ISSUE TITLE
Improve readability of DP best practices

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/superoffice-docs#1205] opened 2024-05-31 07:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of idea is it?

Add or revise existing page

### Who is it for?

Developer

### Which area (SuperOffice entity) is this related to?

Other

### Description

The best practices page in the developer portal docs is hard to digest.

Consider splitting it in multiple sub-pages. Give examples

**Comment by ejfasting** [comment] 2024-06-27 11:25
I suggest the following: 

- [ ] Remove [Tenant availability](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#tenant-availability), this is duplicate of sub-page [Tenant status](https://docs.superoffice.com/en/developer-portal/best-practices/tenant-status/index.html)? At least migrate documentation over to the sub-page and reference it in index.md. 
- [ ] Remove [How to check status](https://docs.superoffice.com/en/developer-portal/best-practices/tenant-status/check-status.html) sub-page, as its duplicate of [Tenant status](https://docs.superoffice.com/en/developer-portal/best-practices/tenant-status/index.html).
- [ ] Rename [Credential manager](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#credential-management) to "Ticket/Token expiration". Move to sub-page (?) and reference external (Microsoft?) documentation for 'Sliding expiration'. 
- [ ] Create sub-page for [Api usage](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#api-usage)
- [ ] Create sub-page for [Count](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#count). Possibly rename to something general (Filters/query-optimizations?) and include [Use filters](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#use-filters) and [Optimization](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#optimization)
- [ ] Create sub-page for webhooks and move [webhooks](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#webhooks) and [tenant status webhook](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#tenant-status-webhook).
- [ ] Create sub-page for [Logging](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#logging)
- [ ] Create sub-page for [Searching](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#searching)
- [ ] Reference the new sub-pages in index.md

'Best practices' contains a lot of valuable information, but not everything is related to the Developer portal itself.. We could consider moving, for example, [Searching](https://docs.superoffice.com/en/developer-portal/best-practices/index.html?tabs=create-rest#searching) to [Api](https://docs.superoffice.com/en/api/overview/index.html) (?)

**Closed** 2024-08-09 11:35 UTC
Labels: doc-idea, online-dev, developer-portal
